name: GitHub Stats

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Generate README.md
      run: |
        echo "## GitHub Stats" >> README.md
        echo "" >> README.md
        echo "[![](https://github-readme-stats.vercel.app/api?username={{GraceAnyango}}&count_private=true&show_icons=true&theme=radical)](https://github.com/{{YOUR_GITHUB_USERNAME}})" >> README.md

    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Add GitHub stats"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
